# Generated by Django 4.2 on 2023-04-08 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('breed', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('owner_name', models.CharField(max_length=40)),
            ],
        ),
    ]
