# Generated by Django 4.2 on 2023-04-09 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppJavi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dogs',
            new_name='Dog',
        ),
    ]
